#!/bin/bash
#
# Copyright (C) 2021 Holger Klemm
#
#
# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.


for i in weedo_x40_0.4_3djake_PLA*
do 
Farbe=`echo "$i" | cut -d'_' -f6`
sed -i 's/yellow/'"$Farbe"'/g' $i
done
